### ISSUE TITLE
undefined: pcapgo.OpenEthernet

### ISSUE THREAD

**Issue by bkaradzic** [rtr7/router7#1]
I'm running into issue while building:
src/github.com/rtr7/router7/cmd/captured/captured.go:48:18: undefined: pcapgo.OpenEthernet

I can't find `OpenEthernet` function in github.com/google/gopacket, there is only OpenLive, OpenOffline.

**Comment by bkaradzic** [comment]
I poked pcapgo module to just skip OpenEthernet, now getting:
`runtime.main_main·f: function main is undeclared in the main package`

I'm building with:
go version go1.11beta1 linux/amd64

**Comment by voltagex** [comment]
https://travis-ci.org/rtr7/router7/jobs/403967134#L522 shows it's a patch added from https://patch-diff.githubusercontent.com/raw/google/gopacket/pull/470.patch

**Comment by bkaradzic** [comment]
That worked! Thanks!
