### ISSUE TITLE
WireGuard support

### ISSUE THREAD

**Issue by stapelberg** [rtr7/router7#14]
Filing this for tracking the ongoing work.

Current status:
* [x] <s>include WireGuard kernel patch in https://github.com/rtr7/kernel</s>
* [x] use Linux ≥ 5.6
* [x] WireGuard netlink package
* [x] make netconfigd read a config file and create/configure WireGuard interfaces
* [x] netconfig: switch to wgctrl-go package
* [ ] netconfig: IPv4/IPv6 address/route config for wireguard interfaces

**Comment by mdlayher** [comment]
Just noticed you added this!  You may be interested in: https://github.com/mdlayher/wireguardctrl.

**Comment by stapelberg** [comment]
That package is now at https://github.com/WireGuard/wgctrl-go. We should probably switch to it.

**Comment by stapelberg** [comment]
Wireguard setup broke with kernel update https://github.com/rtr7/kernel/commit/7dbe98e79262cf830c2fe50515be326642ed3290:

```
2019/07/15 09:06:11 netconfigd.go:169: wireguard: netlink receive: invalid argument
```

strace reveals:
```
[pid  1011] <... recvmsg resumed> {msg_name={sa_family=AF_NETLINK, nl_pid=0, nl_groups=00000000}, msg_namelen=112->12, msg_iov=[{iov_base={{len=212, type=NLMSG_ERROR, flags=0, seq=881650684, pid=978}, {error=-EINVAL, msg={{len=192, type=0x1b /* NLMSG_??? */, flags=NLM_F_REQUEST|NLM_F_ACK, seq=881650684, pid=978}, "\x01\x01\x00\x00\x08\x00\x02\x00\x77\x67\x30\x00\x08\x00\x05\x00\x00\x00\x00\x00\x24\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00"...}}}, iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 212
```

Not entirely sure what’s going on here, but haven’t looked closely yet.

**Comment by stapelberg** [comment]
I split the remaining work into use-case specific issues https://github.com/rtr7/router7/issues/51 and https://github.com/rtr7/router7/issues/52 and will call this one done.
