### ISSUE TITLE
implement DNSSL in cmd/radvd

### ISSUE THREAD

**Issue by stapelberg** [rtr7/router7#45]
https://tools.ietf.org/html/rfc6106#section-5.2

cc @mdlayher 

I think we talked about this but then I didn’t file an issue? This could be a good thing to do on stream.

**Comment by masihtehrani** [comment]
@stapelberg @mdlayher 
I'd like to work on it
can you more explain about the issue

**Comment by stapelberg** [comment]
I can do that if we end up not working on this on stream on Saturday.

The effort to explain this significantly outweighs just doing it, and you’ll be able to watch us do it (either live on https://www.twitch.tv/mdlayher or in the recording).

**Comment by mdlayher** [comment]
Indeed, this will be a ~5-10 line change so probably not worth having someone else do unfortunately when Michael and I have plans to work on this in a couple of days. Thanks for reaching out though.

**Comment by masihtehrani** [comment]
> Indeed, this will be a ~5-10 line change so probably not worth having someone else do unfortunately when Michael and I have plans to work on this in a couple of days. Thanks for reaching out though.

Ok, have best for you 👍

**Comment by stapelberg** [comment]
fixed with commit fe68c2dd524851208aa4ff23b0ba31700fac3cb6
