### ISSUE TITLE
Container Manager

### ISSUE THREAD

**Issue by SuperQ** [rtr7/router7#60]
It would be interesting to be able to run containers on the router as a way to manage services like reverse proxies, media servers, etc.

Perhaps integrate podman?

**Comment by stapelberg** [comment]
There’s some prior discussion at https://github.com/gokrazy/gokrazy/issues/44, where I think this feature should be implemented (if at all)

Please follow up there if you’re interested! Thanks :)

**Comment by SuperQ** [comment]
Oh, great, I didn't realize that this project was built on top of gokrazy. Thanks!
