### ISSUE TITLE
Nat66 or Natv6p

### ISSUE THREAD

**Issue by Morta1985** [rtr7/router7#67]
Is there a possibility to do Nat66 or something equal to give fix IPv6 to a Client?

**Comment by stapelberg** [comment]
If you need a globally reachable static IPv6 address, configure your operating system to use the IPv6 token approach: https://serverfault.com/a/968644

If you need a locally reachable static IPv6 address, configure a unique local address: https://en.wikipedia.org/wiki/Unique_local_address

In neither case do you need any form of NAT :)
