### ISSUE TITLE
Turris Omnia support ?

### ISSUE THREAD

**Issue by xerc** [rtr7/router7#75]
@stapelberg saw your talk about "Why I wrote my own rsync" and wonder if Omnia might work (no need for >1Gbit in `DE` yet)

**Comment by stapelberg** [comment]
Please see https://github.com/rtr7/router7/issues/2 for the general situation of running router7 on other hardware than an x86 PC. 

As long as you’re willing to get gokrazy to boot on your device, not many other changes should be necessary. Others have done it for the older non-64bit Raspberry Pis, or for the Odroid, see also https://gokrazy.org/platforms/, but it depends on the amount of time, motivation and experience you have :)
