### ISSUE TITLE
documentation of setup issues

### ISSUE THREAD

**Issue by dezren39** [rtr7/router7#76]
hello!

I got this project building and running, thank you it is great.

My experience with the install script differed slightly, I'm using fedora && it's silverblue.

That said, some of this may be unrelated to that. I made a repo for the fixes I made:

https://github.com/developing-today/rtr7-install

I don't have time to change it here, and also I'm not sure if all of it is relevant to you.

If I get some more time I may look into a proper pr, but I wanted to get this to you in the meantime.

**Comment by stapelberg** [comment]
Thanks for documenting this. I pushed commit fb08bb280c04e3d075ef1c5a29ed1221d901eb22, which should help with the WireGuard issue.

The rest looks like steps to set up Go on Fedora AFAICT, nothing we can do on our end to make that easier. Not sure why you need to touch the GOPROXY environment variable, I thought the default should work out of the box.

Let me know if anything is left to be done in router7 :)
