### ISSUE TITLE
Status of other ISPs?

### ISSUE THREAD

**Issue by c-edw** [rtr7/router7#8]
Hi. 

>It comes with all the services required to make a fiber7 internet connection work (DHCPv4, DHCPv6, DNS, etc.).

I'd like to ask whether router7 works with ISPs other than fiber7. The README is phrased in a way that makes it sound as though ISPs have different requirements.

Thanks.

**Comment by c-edw** [comment]
I see. Is there a method to finding out which my ISP uses, or will it require a phone call? Thanks.

**Comment by c-edw** [comment]
Virgin Media on a fiber (I think....) connection. The router is a purchased consumer router rather than one from an ISP.

**Comment by stapelberg** [comment]
At this point, I think it’s best to clearly set expectations: router7 is a project which is not meant to be usable by end-users. As the README states, it’s published as a tech demo. If you want to actually use it, of course you’re free to, but from the answers you’re giving, I extrapolate that it will likely be a frustrating experience.

If you’re still interested, I’d recommend to read about building your own router from a PC and well-established router/firewall appliances. See e.g. https://arstechnica.com/gadgets/2016/04/the-ars-guide-to-building-a-linux-router-from-scratch/, or google for keywords like OpenWrt or pfsense. Once you’ve done that, you should be in a much better position to consider router7.

Thanks for understanding,

**Comment by c-edw** [comment]
Indeed, I can look under the hood, but they are large codebases. The core implementation of what a router really needs to do (NAT, DHCP, etc) will be buried - and that's the part I would really like to learn more about. Regardless, I will take your advice and try setting up a custom router, as well as Wireshark. 

I really appreciate your help. I will close this issue.

**Comment by discordianfish** [comment]
@stapelberg Regarding pppoe, which I guess would support many ISPs out the box:
1. Do you think exisiting libraries like https://github.com/katalix/go-l2tp would be sufficient to implement that?
2. Would you be open for PRs to implement this?

**Comment by stapelberg** [comment]
> * Do you think exisiting libraries like https://github.com/katalix/go-l2tp would be sufficient to implement that?

Sorry, I have no idea. My PPPOE days are behind me, and I’m not looking to get back into it. L2TP does not ring a bell to me.

> 2\. Would you be open for PRs to implement this?

Yes, but I would prefer that the pppoe program be developed in your own repository (to begin with, at least — this gives you maximum velocity and flexibility).

If you need to change parts of router7 itself, feel free to send a PR.

If pppoe works well and turns out to be popular, I’m open to merging it at a later point.
