### ISSUE TITLE
Can it compile for Windows as well?

### ISSUE THREAD

**Issue by lonnietc** [rtr7/router7#81]
Hello,

I like many applications in Golang since the cross-compile very well.

The project that I have now needs a cross-platform router to run on Windows and Linux with DHCP, Bridging, and with (IPv4, IPv6). I would also like to investigate using Wireguard as well since it seems to be extremely fast.

I came across your router7 project and it seems to be really good although I am guessing that it might need some modifications to work as I need.

Any thoughts?
Thanks

**Comment by stapelberg** [comment]
Hey! 

router7 is a collection of programs that configure the Linux kernel’s network routing abilities. Therefore, it can only run on Linux, and does not implement any network routing itself. 

If you need network abilities in userspace (and therefore available cross-platform), I would encourage you to look at gvisor’s netstack library instead, which Tailscale uses: https://tailscale.com/kb/1177/kernel-vs-userspace-routers/

Hope this helps
